name: Compile the showcases
'on':
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
    - name: Setup Python environment for sltx
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup and run sltx-install
      run: |
        pip install sltx
        echo "tx-default" | sltx docker
    - name: Compile the Documents
      run: |
        echo $(pwd)
        sltx compile --root --profile "tx-default" "examples/showcase-shortcuts.tex"
        find .
        sltx compile --root --profile "tx-default" "examples/showcase-glossary.tex"
        find .
        echo $(pwd)
    - name: Commit
      run: |
        echo $(pwd)
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f "showcase-shortcuts.pdf" "showcase-glossary.pdf"
        git commit -m "Newly compiled data"
        echo $(pwd)
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
